<div class="content">
      <div class="main">
      <div class="w100"><img src="<?php echo base_url(); ?>assets/home/images/jx.jpg" border="0"></div>
        <div id="" class="main_left">
        <div>
	        <h2 style=""><span>&nbsp;&nbsp;</span>关于凌霄</h2>
	         <ul class="main_left_list">
	            <li><a class="main_nav_left" href="?id=11" style="" title="公司概况"><span class="">&nbsp;&nbsp;</span>公司概况</a></li>
				<li><a class="main_nav_left" href="?id=8" style="" title="公司荣誉"><span class="">&nbsp;&nbsp;</span>公司荣誉</a></li>
				<li><a class="main_nav_left" href="?id=62" style="" title="发展历程"><span class="">&nbsp;&nbsp;</span>发展历程</a></li>
				<li>
					<a class="main_nav_left" style="" title="企业文化"><span class="">&nbsp;&nbsp;</span>企业文化</a>
					<ul>
						<li><a class="main_nav_left" href="?id=64" style="" title="人才理念"><span class="">&nbsp;&nbsp;</span>人才理念</a></li>
						<li><a class="main_nav_left" href="?id=67" style="" title="人才招聘"><span class="">&nbsp;&nbsp;</span>人才招聘</a></li>	
				   </ul>	
				</li>
				<li><a class="main_nav_left" style="" title="人力资源"><span class="">&nbsp;&nbsp;</span>人力资源</a>
					<ul>
						<li>
							<a class="main_nav_left" style="" title="人才理念"><span class="">&nbsp;&nbsp;</span>人才理念</a>
							<ul>
								<li><a class="main_nav_left" href="?id=64" style="" title="人才理念"><span class="">&nbsp;&nbsp;</span>人才理念</a></li>
								<li><a class="main_nav_left" href="?id=67" style="" title="人才招聘"><span class="">&nbsp;&nbsp;</span>人才招聘</a></li>	
						   </ul>	
						</li>
						<li><a class="main_nav_left" href="?id=67" style="" title="人才招聘"><span class="">&nbsp;&nbsp;</span>人才招聘</a></li>	
					</ul>	
				</li>
				<li><a class="main_nav_left" href="?id=65" style="" title="地理位置"><span class="">&nbsp;&nbsp;</span>地理位置</a></li>
				<li><a class="main_nav_left" href="contactUs.php" style="" title="联系信息"><span class="">&nbsp;&nbsp;</span>联系信息</a></li>
			</ul>
		</div>
        </div>
     	<div class="main_right">
     	      <div class="position">·<a href="/">首页</a> -&gt; <a href="/products/">产品展示</a> -&gt; <h1>CHL，CHLK，CHLF（T）轻型卧式多级离心泵</h1></div>
     	     <div>
     	      <p><div style="display: inline-block;width: 90%;">新闻一</div> <div style="text-align: right;display: inline-block;">时间</div> </p>
     	      
     	      </div>
     	      <div class="main_right_center1">
     	      	<div class="main_banner">
     	      	<img alt="banner" src="<?php echo base_url(); ?>assets/home/images/banner.jpg"></div>
     	      	<div style="margin:12px;"><p><span style="font-family: 黑体; font-size: 15pt"></span></p>
					<p><span style="line-height: 150%; font-family: 宋体; font-size: 14pt"></span></p>
					<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="line-height: 150%; font-family: 宋体; font-size: 14pt"><strong>广东凌霄泵业股份有限公司</strong></span></p>
					<p><span style="line-height: 150%; font-family: 宋体; font-size: 14pt"><strong><span lang="EN-US"><o:p><strong><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2012年度股东大会的会议通知</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US"><o:p></o:p></span></strong></o:p></span></strong></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt"><strong>全体股东：<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: 23.25pt; margin: 0cm 0cm 0pt; layout-grid-mode: char; mso-layout-grid-align: none" class="MsoNormal"><a name="OLE_LINK4"></a><a name="OLE_LINK3"><span style="mso-bookmark: OLE_LINK4"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">广东凌霄泵业</span></span></a><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">股份有限公司已于<span lang="EN-US">2013</span>年<span lang="EN-US">6</span>月<span lang="EN-US">6</span>日召开董事会会议，会议通过了《关于提请召开<span lang="EN-US">2012</span>年度股东大会的议案》，根据前述董事会会议决议、《中华人民共和国公司法》、《广东凌霄泵业股份有限公司章程》的相关规定，发</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-family: 微软雅黑">出召开</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">广东凌霄泵业</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-family: 微软雅黑">股份有限公司</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">2012</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">年度股东大会<span style="color: black">的通知如下 ：<span lang="EN-US"><o:p></o:p></span></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt"><strong>一、会议时间和会议地点<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: -57pt; margin: 0cm 0cm 0pt 80.95pt; mso-char-indent-count: -4.75; tab-stops: 27.0pt; mso-para-margin-left: 2.28gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">会议时间：<span lang="EN-US">2013</span>年<span lang="EN-US">6</span>月<span lang="EN-US">26</span>日上午<span lang="EN-US">10</span>：<span lang="EN-US">00<o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: -57pt; margin: 0cm 0cm 0pt 80.95pt; mso-char-indent-count: -4.75; tab-stops: 27.0pt; mso-para-margin-left: 2.28gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">会议地点：广东凌霄泵业股份有限公司<span style="color: black">办公楼四楼会议室</span><span style="color: red" lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1; tab-stops: 38.25pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt"><strong>二、会议主持<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0; tab-stops: 32.25pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">会议主持人：刘子庚<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1; tab-stops: 32.25pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">三、<strong>会议主要议案<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US">1</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">、《</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-weight: bold">关于董事会工作报告的议案》<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">2</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">、《关于公司<span lang="EN-US">2012</span>年年度审计报告的议案》<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">3</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">、《</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-font-kerning: 0pt">关于增资<span lang="EN-US">465.05</span>万股的议案》<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">4</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">、《章程修正案》<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">5</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">、《关于聘请天衡会计师事务所为审计机构的议案》<span style="color: black; mso-bidi-font-weight: bold" lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1" class="MsoNormal"><span><strong>四、会议出席人<span style="color: black" lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="margin: 0cm 0cm 0pt" class="MsoBodyTextIndent"><span style="font-family: 宋体"><font size="3">全体股东、董事、监事、高级管理人员。<span lang="EN-US"><o:p></o:p></span></font></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt"><strong>五、出席会议的办法<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">1</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、股东可以亲自出席</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US">2012</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">年度股东大会</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">，也可以委托代理人代为出席和表决。<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">2</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、股东委托代理人应当以书面形式作出，授权委托书（式样附后）由委托人的法定代表人或法定代表人以书面形式委任的代理人签署，并应加盖法人单位公章。<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">3</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、法定代表人出席会议的，应出示本人身份证</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-size: 13.5pt">明（身份证、护照或台胞证）<span style="color: black">、能证明其具有法定代表人资格的有效证明和持股凭证（股东卡）；委托代理人出席会议的，代理人应出示本人身份证明、法人股东单位的法定代表人依法出具的书面委托书。<span lang="EN-US"><o:p></o:p></span></span></span></p>
					<p style="line-height: 150%; margin: 0cm -6.7pt 0pt 0cm; mso-outline-level: 1; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt"><strong>六、会议登记事项<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: -18pt; margin: 0cm -6.7pt 0pt 42pt; tab-stops: list 42.0pt; mso-para-margin-left: 42.0pt; mso-para-margin-right: -.64gd; mso-para-margin-top: 0cm; mso-para-margin-bottom: .0001pt; mso-list: l0 level1 lfo1" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt; mso-bidi-font-family: 宋体" lang="EN-US"><span style="mso-list: Ignore">1、</span></span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">登记事项<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">出席公司</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US">2012</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">年度股东大会</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">的股东的法定代表人携带法人证明（营业执照）、法定代表人的身份证明（身份证或护照等）；股东携带身份证明（身份证或护照等）；委托代理人出席的携带法人股东单位法人证明、法定代表人或股东依法出具的书面委托书、代理人的身份证明。<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">2</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、登记办法<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">出席公司</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US">2012</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">年度股东大会</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">的股东或其代理人可直接于本次股东大会召开日自行前往会场，未经事前联系的，应带齐身份证件及股东持股凭证，或在会议召开前，以电话、传真、邮件等方式通知会议联系人参会与否。<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">3</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-size: 13.5pt">会议登记截止时间：</span><st1:chsdate w:st="on" year="2013" month="6" day="26" islunardate="False" isrocdate="False"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US">2013</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">年<span lang="EN-US">6</span>月<span lang="EN-US">26</span>日</span></st1:chsdate><span style="line-height: 150%; font-family: 宋体; font-size: 12pt"> </span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US"><o:p></o:p></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US">4</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">、</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-size: 13.5pt">登记地点：</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">广东凌霄泵业股份有限公司四楼会议室</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt" lang="EN-US"><o:p></o:p></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm -6.7pt 0pt 0cm; mso-char-indent-count: 2.0; mso-para-margin-right: -.64gd" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">如果超过登记截止时间未办理登记，视为未出席</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt" lang="EN-US">2012</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">年度股东大会</span><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-size: 13.5pt">，无权参与表决。<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt"><strong>七、会务联系事项<span lang="EN-US"><o:p></o:p></span></strong></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">联系地点： <span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">广东凌霄泵业</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">股份有限公司<span style="color: black">办公楼四楼会议室</span><span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US"><span style="mso-spacerun: yes">&nbsp;&nbsp;&nbsp; </span></span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">联系电话：<span lang="EN-US">7706083</span>、<span lang="EN-US">7706183<o:p></o:p></span></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt">联 系 人：刘子庚、张柳红<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="line-height: 150%; margin: 0cm 0cm 0pt; mso-outline-level: 1" class="MsoNormal"><span><strong>八、其他事项<o:p></o:p></strong></span></p>
					<p style="line-height: 150%; text-indent: 24pt; margin: 0cm 0cm 0pt; layout-grid-mode: char; mso-layout-grid-align: none; mso-char-indent-count: 2.0" class="MsoNormal"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt">无</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt" lang="EN-US"><o:p></o:p></span></p>
					<p style="text-align: right; line-height: 150%; margin: 0cm 0cm 0pt; layout-grid-mode: char; mso-layout-grid-align: none" class="MsoNormal" align="right"><span style="line-height: 150%; font-family: 宋体; color: black; font-size: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt">广东凌霄泵业股份有限公司董事会<span lang="EN-US"><o:p></o:p></span></span></p>
					<p style="text-align: right; line-height: 150%; margin: 0cm -7.65pt 0pt 0cm; layout-grid-mode: char; word-break: break-all; mso-layout-grid-align: none; mso-para-margin-right: -.73gd" class="MsoNormal" align="right"><st1:chsdate w:st="on" year="2013" month="6" day="6" islunardate="False" isrocdate="False"><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt" lang="EN-US">2013</span><span style="line-height: 150%; font-family: 宋体; font-size: 12pt; mso-bidi-font-family: 宋体; mso-font-kerning: 0pt">年<span lang="EN-US">6</span>月<span lang="EN-US">6</span>日</span></st1:chsdate><span style="font-family: 宋体" lang="EN-US"><o:p></o:p></span></p>
					<p style="text-align: center; line-height: 150%; margin: 0cm 0cm 0pt" class="MsoNormal" align="center">&nbsp;</p>
				</div>
     	      </div>
     	     
     	</div>
     	<div class="clear"></div>
     	 <div class="w100"><img src="<?php echo base_url(); ?>assets/home/images/jx.jpg" border="0"></div>
      </div>
    </div>